name: Build Debian packages
on:
  push:

jobs:
  deb:
    runs-on: ${{ matrix.os }}
    container: debian:${{ matrix.release }}
    strategy:
      fail-fast: false
      matrix:
        release:
          - bullseye
          - bookworm
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y autoconf automake biber git git-buildpackage      \
              help2man libflint-dev libtool make texlive-bibtex-extra          \
              texlive-fonts-extra texlive-fonts-recommended texlive-latex-base \
              texlive-latex-extra texlive-latex-recommended                    \
              texlive-plain-generic texlive-science
      - name: Clone repository
        run: |
          git clone https://salsa.debian.org/math-team/msolve
          cd msolve
          git checkout debian/${{ matrix.release }}
      - name: Build package
        run: |
          cd msolve
          uscan --verbose --rename --force-download
          dpkg-buildpackage
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: msolve-debian-${{ matrix.release }}-${{ matrix.os }}
          path: |
            *.buildinfo
            *.changes
            *.deb
            *.dsc
            *.tar.*
